sion/regis_organisasi/urls.py
from django.conf.urls import url
from .views import index, index_after, registrasi, validate_email
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^after_regis', index_after, name='index_after'),
    url(r'^register', registrasi, name='register'),
    url(r'^validate-email', validate_email, name='validate-email'),
]

sion/sion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import login.urls as login
import regis_organisasi.urls as regis_organisasi

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(login, namespace='login'),
    url(r'^registrasi/', include(regis_organisasi, namespace='regis_organisasi')
]

sion/regis_organisasi/models.py
from django.db import models

# Create your models here.

sion/regis_organisasi/views.py
from django.shortcuts import render
from django.db import connection
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import messages
import psycopg2
# Create your views here.

response = {}
def index(request):
	return render(request, 'regis_organisasi.html')

def index_after(request):
	return render(request, 'after_regis.html')

@csrf_exempt
def validate_email(request):
	if request.method=='POST':
		npm = request.POST[email]
		cursor = connection.cursor()
		cursor.execute("SET search_path to SION;")
		cursor.execute('select email_organisasi from organisasi')
		email_org = cursor.fetchall()
		for e in email_org :
			if e[0] == npm:
				taken = True
				break
			else :
				taken = False

	data = {
		'is_taken': taken
	}
	return JsonResponse(data)

# def __init__(self):
#                 try:
#                         self.connection = psycopg2.connect(
#                                 dbname="purwoaji", user="purwoaji", password="paris1732011")
#                         self.connection.autocommit = True
#                         self.cursor = self.connection.cursor()
#                         print("test")
#                 except:
#                         print("Cannot connect to database")

# def registrasi(request):
# 	if (request.method=='POST'):
# 		connection = psycopg2.connect('dbname=purwoaji', 'user=purwoaji')
# 		mark = connection.cursor()
# 		statement = 'INSERT INTO ' + 'organisasi' + ' VALUES (' + request.POST['email'] + ',' + request.POST['web'] + ',' + request.POST['nama-org'] + ',' + request.POST['provinsi'] + ',' + request.POST['kabupaten'] + ',' + request.POST['kecamatan'] + ',' + request.POST['kelurahan'] + ',' + request.POST['kode-pos'] + ',' + 'Tidak Aktif' + ')'
# 		mark.execute(statement)
# 		connection.commit() 
# 		return render(request, 'after_regis.html')
@csrf_exempt
def registrasi(request):
	print("mask form")
	email = request.POST['email']
	web = request.POST['web']
	nama_org = request.POST['nama-org']
	provinsi = request.POST['provinsi']
	kabupaten = request.POST['kabupaten']
	kecamatan = request.POST['kecamatan']
	alamat_lengkap = request.POST['alamat-lengkap']
	kode_pos = request.POST['kode-pos']
	email_pengurus = request.POST['email-pgr']

	if request.method=='POST' :
		cursor = connection.cursor()
		cursor.execute("SET search_path to SION;")

		cursor.execute('select email_organisasi from organisasi')
		email_org = cursor.fetchall()
		taken = True
		for e in email_org :
			if e[0] == email:
				taken = False
				break
			else :
				taken = True

		cursor.execute('select nama from organisasi')
		nama_org = cursor.fetchall()
		point = True
		for j in nama_org :
			if j[0] == nama_org:
				point = False
				break
			else :
				point = True

		cursor.execute('select email from sion.user')
		email_pgr = cursor.fetchall()
		pointer = True
		for i in email_pgr:
			if i[0] == email_pengurus:
				pointer = True
				break
			else :
				pointer = False


		if taken and point and pointer :
			print("HOLAAAAAA")
			
			cursor.execute("SELECT count(*) FROM organisasi")
			response['nomor_reg'] = cursor.fetchone()[0]
			print(response['nomor_reg'])
			cursor.execute("SELECT password FROM SION.user WHERE email='" +email_pengurus+ "'")
			response['password'] = cursor.fetchone()[0]
			print(response['password'])
			response['email_pengurus'] = email_pengurus
			print(response['email_pengurus'])
			cursor.execute("INSERT INTO organisasi (email_organisasi,website,nama,provinsi,kabupaten_kota,kecamatan,kelurahan,kode_pos,status_verifikasi) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, 'Aktif')", [email,web,nama_org,provinsi,kabupaten,kecamatan,alamat_lengkap,kode_pos])
			cursor.execute("INSERT INTO pengurus_organisasi (email, organisasi) VALUES (%s,%s)", [email_pengurus,email])
			html = 'after_regis.html'
			return render(request, html, response)
		else :
			print("JAAKAKAKAK")
			messages.error(request, "Input yang dimasukkan sudah terdaftar")
		return HttpResponseRedirect("/regis_organisasi")

sion/regis_organisasi/templates/after_regis.html
{% extends "layout/base.html" %}
{% block content %}
<style>
	.card {
	    /* Add shadows to create the "card" effect */
	    box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
	    transition: 0.3s;
	}

	/* On mouse-over, add a deeper shadow */
	.card:hover {
	    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
	}

	/* Add some padding inside the card container */
	.contain {
	    padding: 2px 16px;
	}
</style>
<div class="card">
  <div class="contain">
    <h4><b>Nomor Registrasi : {{ nomor_reg }}</b></h4> 
    <p>Email Pengurus : {{ email_pengurus }}</p>
    <p>Password : {{ password }}</p> 

    <!-- <h4><b>Nomor Registrasi : 12345</b></h4> 
    <p>Email Pengurus : afwan@gmail.com</p>
    <p>Password : qwerty</p>  -->

  </div>
</div>
{% endblock %}

sion/regis_organisasi/templates/regis_organisasi.html
{% extends "layout/base.html" %}
{% block content %}
<!-- <style>
    .center_screen {
        position: absolute;
        width: 500px;
        height: 50px;
		font-size : 40px;
        top: 50%;
        left: 50%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
		color : #040F0F;
    }
</style>
<div class="center_screen">
    <p class="status" id="test">Hello, this is Purwo.</p>
</div> -->
<!-- <style>
    .right_screen {
        position: ;
        width: 200px;
        height: 50px;
        font-size : 40px;
        top: 20%;
        left: 80%;
        margin-left: -250px; /* margin is -0.5 * dimension */
        margin-top: -25px;
        color : #040F0F;
    }
</style> -->
<form method="POST" action="{% url 'regis_organisasi:register' %}">
    {% csrf_token %}
  <div class="container">
    <h2>Register Your Organitation</h2>
    <p>Please fill in this form to create an account.</p>
    <hr>

    <label for="nama-org"><b>Nama Organisasi</b></label>
    <input type="text" placeholder="Enter Organization Name" name="nama-org" required>

    <label for="web"><b>Website</b></label>
    <input type="text" placeholder="Enter Website" name="web" required>

    <label for="email"><b>Email</b></label>
    <input type="text" placeholder="Enter Email" name="email" required>
    
    <label for="kecamatan"><b>Kecamatan</b></label>
    <input type="text" placeholder="Enter Kecamatan" name="kecamatan" required>
    
    <label for="kabupaten"><b>Kabupaten</b></label>
    <input type="text" placeholder="Enter Kabupaten" name="kabupaten" required>
    
    <label for="provinsi"><b>Provinsi</b></label>
    <input type="text" placeholder="Enter Provinsi" name="provinsi" required>
    
    <label for="kode-pos"><b>Kode Pos</b></label>
    <input type="text" placeholder="Enter Kode Pos" name="kode-pos" required>
    
    <label for="alamat-lengkap"><b>Jalan/Desa/Kelurahan/No.Rumah</b></label>
    <input type="text" placeholder="Enter Alamat Lengkap" name="alamat-lengkap" required>

    <label for="tujuan-org"><b>Tujuan Organisasi</b></label>
    <input type="text" placeholder="Enter Tujuan Organisasi" name="tujuan-org" required>

    <label for="nama-pgr"><b>Nama Pengurus</b></label>
    <input type="text" placeholder="Enter Nama Pengurus" name="nama-pgr" required>

    <label for="email-pgr"><b>Email Pengurus</b></label>
    <input type="text" placeholder="Enter Email Pengurus" name="email-pgr" required>

    <label for="alamat-pgr"><b>Alamat Pengurus</b></label>
    <input type="text" placeholder="Enter Alamat Pengurus" name="alamat-pgr" required>

    <button type="submit" class="registerbtn">Register</button>

    <!-- <button type="submit" class="registerbtn" href="after_regis">Register</button> -->

      <div class="container signin">
    <p>Already have an account? <a href="#">Sign in</a>.</p>
  </div>
  </div>
  

</form>
{% endblock %}


{% block javascript %}
<script type="text/javascript">
    $("#email").change(function () {
        console.print('haha');
        console.log( $(this).val() );
        email = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "regis_organisasi:validate-email" %}',
            data: {
                'email': email
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Organisasi dengan email ini sudah ada");
                }
            }
        });
    });
</script>

{% endblock %}